### ISSUE TITLE
EBIClient returns KeyError: 'response'

### ISSUE THREAD

**Issue by PoGibas** [cthoyt/ols-client#7]
I encountered an issue while trying to retrieve ontologies using the `ols-client` library. 

```
from ols_client import EBIClient

ebi_client = EBIClient()
ebi_client.search("Orbitrap Eclipse")
```

I have experienced the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/XXX/opt/anaconda3/envs/XXX/lib/python3.9/site-packages/ols_client/client.py", line 167, in search
    return self.get_json("/search", params=params)["response"]["docs"]
KeyError: 'response'
```

This code used to work as expected in December 2022.  Can you please help me to solve this issue?

```
# > poetry show ols_client
 name         : ols-client                                  
 version      : 0.1.4                                       
 description  : A client to the EBI Ontology Lookup Service 
```

**Comment by cthoyt** [comment]
This might be an issue from the new ols version. Can you try checking that this endpoint works the same as before? Otherwise we can ping James who is the ols developer

**Comment by cthoyt** [comment]
hi @PoGibas please see #8 and let me know if that fixes your issue

**Comment by PoGibas** [comment]
Dear Charles, thank you!
This seems to fix my issue. Thanks for a fast solution
